---
title: "Interactive Session"
author: "Matteo Torres"
format: html
editor_options: 
  chunk_output_type: console
---

```{r}
# load packages
library(tidyverse)
library(here)
library(janitor)
library(patchwork)
library(ggrepel)
library(gghighlight)
library(paletteer)
library(ggExtra)
library(ggbeeswarm)
```

```{r}
lizards <- read_csv(here("data_tidy", "lizards.csv"))
```

```{r}
ggplot(data = lizards, aes(x = total_length, y = weight)) +
  geom_point()

ggplot(data = lizards) +
  geom_point(aes(x = total_length, y = weight))

ggplot() +
  geom_point(data = lizards, aes(x = total_length, y = weight))
```

```{r}
ggplot(data = lizards, aes(x = total_length)) + 
  geom_histogram()
```

```{r}
ggplot(data = lizards, aes(y = common_name, x = weight)) +
  geom_jitter()
```

```{r}
ggplot(data = lizards, aes(x = weight)) +
  geom_histogram(color = "purple",
                 fill = "green",
                 linewidth  = 2,
                 linetype = "dotted")
```

```{r}
ggplot(data = lizards, aes(x = total_length, y = weight)) +
  geom_point(color = "#DDC3D0",
             fill = "#3E92CC",
             shape = 22,
             size = 1,
             alpha = 0.5)
```

```{r}
ggplot(data = lizards, aes(x = total_length, y = weight)) +
  geom_point(aes(color = common_name,
                 size = total_length),
             alpha = 0.5) +
  scale_color_discrete(type = c("red", "orange", "yellow", "green", "blue", "violet", "black"))
# scale_color_brewer(palette = "Set3")
```

```{r}
ggplot(data = lizards, aes(x = site, y = weight)) + 
  geom_jitter(aes(color = common_name)) +
  theme_light()
# theme_bw()
# theme_minimal()
```

```{r}
ggplot(data = lizards, aes(x = total_length, y = weight)) +
  geom_point() +
  labs(x = "Total Length (mm)",
       y = "Weight (g)",
       title = "Lizard Size")
```

```{r}
ggplot(data = lizards, aes(x = total_length, y = weight)) +
  geom_point() +
  facet_wrap(~common_name, ncol = 3, scales = "free") +
  labs(x = "Total Length (mm)",
       y = "Weight (g)")
```

```{r}
ggplot(data = lizards, aes(x = total_length, y = weight)) + 
  geom_point() +
  facet_grid(sex ~ tail)
```

```{r}
lizards_count <- lizards %>%
  count(common_name) %>%
  rename(n_lizards = n)

ggplot(data = lizards_count, aes (y = fct_reorder(common_name, n_lizards), x = n_lizards)) +
  geom_col()
```

```{r}
ggplot(data = lizards, aes(x = total_length, y = weight)) + 
  geom_point(aes(color = common_name,
                 shape = common_name),
             size = 2) +
  theme_minimal() +
  labs(x = "Total Length (mm)",
       y = "Weight (g)",
       title = "Lizard Size",
       color = "Lizard Species") +
  facet_wrap(~common_name, scales = "free")
```

```{r}
ggplot(data = lizards, aes(y = fct_infreq(common_name))) +
  geom_bar(aes(fill = site)) +
  theme_minimal() +
  labs(x = "Lizard Counts",
       y = "Species Common Name") +
  facet_grid(sex ~ tail)
```

```{r}
ggplot(data = lizards, aes(x = total_length, y = weight)) +
  geom_point() +
  scale_x_continuous(breaks = c(0, 250, 500),
                     limits = c(0, 500)) +
  scale_y_continuous(breaks = seq(from = 0, to = 70, by = 10),
                     limits = c(0,70)) +
  theme_light()
```

```{r}
lizards_counts <- lizards %>%
  mutate(date = lubridate::mdy(date)) %>%
  count(date)

ggplot(data = lizards_counts, aes(x = date, y = n)) +
  geom_line() +
  scale_x_date(breaks = scales::breaks_width("3 years"),
               labels = scales::label_date("'%Y")) +
  labs(x = "Date",
       y = "Number of Lizards (n)")
```

```{r}
ggplot(data = lizards, aes(x = total_length, y = weight)) +
  geom_point(aes(color = weight)) +
  scale_color_steps(low = "red", high = "black")
# scale_color_gradientn(colors = c("orange", "red", "purple", "navy", "black"))
# scale_color_gradient(low = "red", high = "navy")
```

```{r}
p <- ggplot(data = lizards, aes(x = total_length, y = weight)) +
  geom_point()

p +
  theme(panel.grid = element_blank(),
        panel.grid.major = element_line(color = "red"),
        plot.background = element_rect(fill = "pink"),
        text = element_text(size = 12, family = "serif"), 
        axis.text.x = element_text(color = "blue"),
        axis.text.y = element_text(color = "green"),
        panel.background = element_rect(color = "purple", fill = "yellow"))
```

```{r}
p +
  geom_hline(yintercept = 40, color = "blue", linetype = "dashed") +
  geom_vline(xintercept = 100, color = "red") +
  annotate("text", x = 100, y = 50, label = "COOL!", color = "purple") +
  annotate("text", x = 350, y = mean(lizards$weight), label = "Mean Weight")
```

```{r}
mono <- read_csv(here("data_tidy", "mono.csv"))

ggplot(data = mono, aes(x = year, y = lake_level)) +
  geom_rect(aes(xmin = 1941,
                xmax  = 1983,
                ymin = 6350,
                ymax = 6440),
            fill = "gray90", alpha = 0.5) +
  geom_line() +
  labs(x = "Year",
       y = "Lake Surface Level\n(feet above sea level)",
       title = "Mono Lake (1850 - 2017)",
       caption = "Data: Mono Basin Clearinghouse") +
  theme_minimal() +
  scale_y_continuous(limits = c(6350, 6440),
                     breaks = c(6370, 6400, 6430),
                     labels = scales::label_comma()) +
  scale_x_continuous(limits = c(1850, 2020),
                     breaks = seq(1850, 2010, by = 20),
                     expand = c(0,0)) +
  geom_hline(yintercept = 6360, linetype = "dashed") +
  annotate("text", x = 1910, y = 6370, label = "Decreased shrimp abundance expected\n(6,360 feet above sea level)") +
  annotate("text", x = 1962, y = 6425,
           label = "unrestricted diversions\n(1941 - 1983)",
           size = 3)
```

